-- ----------------------------------------------------------------------------
-- Phase 9: cron idempotency, intake atomicity + provenance, HEIC plumbing,
--          per-IP rate limit moves to the DB.
--
-- Five concrete pieces:
--
-- (A) Cron idempotency. A rent-charge generator that runs twice (or two
--     workers race) MUST NOT double-bill. Enforced at the DB: a unique
--     partial index on (source_schedule_id, period_start) rejects a second
--     attempt for the same schedule+period. Same discipline for the
--     scheduled_task_runs table.
--
-- (B) ip_rate_buckets. The Phase 7 per-IP rate limit was in-memory --
--     resets on restart, useless across multiple instances. Moved to a
--     sliding-window DB table the moment we want >1 instance.
--
-- (C) attachments.derived_from. HEIC transcoding (Phase 9 code in
--     api/src/admin/storage.ts) stores TWO attachment rows: the original
--     HEIC and a derived JPEG. The derived row's derived_from references
--     the original so the provenance is explicit: this JPEG came from
--     that HEIC, computed server-side at upload.
--
-- (D) submit_intake_with_attachment RPC. Folds the attachment INSERT into
--     the same transaction as the request + interaction. ALL THREE rows
--     commit together, attributed to actor='tenant:<token_id>'. The
--     attachment-without-its-photo (and vice versa) failure mode is
--     eliminated; the photo's audit event correctly shows tenant
--     attribution.
--
-- (E) generate_rent_charges / generate_scheduled_task_runs RPCs.
--     audit.actor='system:cron' on every cron-generated row. ON CONFLICT
--     DO NOTHING means re-runs and races are no-ops, not failures.
-- ----------------------------------------------------------------------------

-- ============================================================================
-- (A) Cron idempotency on charges
-- ============================================================================

-- A charge generated by a rent schedule is uniquely identified by
-- (schedule, period_start). Manual charges have source_schedule_id=null
-- and are exempt from this constraint via the partial predicate.
create unique index charges_one_per_schedule_period
  on public.charges (source_schedule_id, period_start)
  where source_schedule_id is not null and period_start is not null;

-- ============================================================================
-- scheduled_task_runs: one row per (task, period). Same dedupe pattern.
-- ============================================================================

create table public.scheduled_task_runs (
  id            uuid primary key default gen_random_uuid(),
  account_id    uuid not null,
  task_id       uuid not null,
  period_start  date not null,
  generated_at  timestamptz not null default now(),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  deleted_at    timestamptz,
  foreign key (account_id, task_id) references public.scheduled_tasks(account_id, id) on delete cascade,
  unique (task_id, period_start),
  unique (account_id, id)
);
create index scheduled_task_runs_account_id_idx on public.scheduled_task_runs (account_id);
create index scheduled_task_runs_task_id_idx on public.scheduled_task_runs (task_id);

alter table public.scheduled_task_runs enable row level security;
alter table public.scheduled_task_runs force  row level security;
create policy scheduled_task_runs_member_all on public.scheduled_task_runs
  for all
  using      (public.is_account_member(account_id))
  with check (public.is_account_member(account_id));

-- Audited like every other domain table.
create trigger scheduled_task_runs_audit
  after insert or update or delete on public.scheduled_task_runs
  for each row execute function public._emit_event();

-- ============================================================================
-- (B) ip_rate_buckets: sliding-window per-IP rate limiter
-- ============================================================================

create table public.ip_rate_buckets (
  ip            text not null check (length(ip) between 1 and 64),
  scope         text not null check (length(scope) between 1 and 32),
  count         int  not null default 0,
  window_start  timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  primary key (ip, scope)
);

-- This table is operational/security infra, not domain. Skip account-scoped
-- RLS; no public access at all -- only the admin client uses it.
revoke insert, update, delete, select on public.ip_rate_buckets from public;
revoke insert, update, delete, select on public.ip_rate_buckets
  from anon, authenticated;

-- Helper: atomically increment the bucket and return the new count. If
-- the existing row's window has expired, reset to 1.
create or replace function public.bump_ip_rate_bucket(
  p_ip          text,
  p_scope       text,
  p_window_sec  int
)
returns int
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count int;
begin
  insert into public.ip_rate_buckets (ip, scope, count, window_start)
    values (p_ip, p_scope, 1, now())
  on conflict (ip, scope) do update
    set count = case
                  when now() - public.ip_rate_buckets.window_start > make_interval(secs => p_window_sec)
                  then 1
                  else public.ip_rate_buckets.count + 1
                end,
        window_start = case
                  when now() - public.ip_rate_buckets.window_start > make_interval(secs => p_window_sec)
                  then now()
                  else public.ip_rate_buckets.window_start
                end,
        updated_at = now()
  returning count into v_count;
  return v_count;
end;
$$;

grant execute on function public.bump_ip_rate_bucket(text, text, int) to service_role;

-- ============================================================================
-- (C) attachments.derived_from
-- ============================================================================
--
-- HEIC originals get a derived JPEG at upload (Phase 9 application code).
-- The derived row points back to the original via derived_from. The
-- composite FK on (account_id, derived_from) keeps the derivation
-- same-account by construction.

alter table public.attachments
  add column derived_from uuid;

alter table public.attachments
  add constraint attachments_derived_from_fk
  foreign key (account_id, derived_from)
  references public.attachments(account_id, id) on delete cascade;

create index attachments_derived_from_idx on public.attachments (derived_from)
  where derived_from is not null;

-- ============================================================================
-- (D) submit_intake_with_attachment RPC
-- ============================================================================
--
-- A superset of submit_intake. Same dedupe behaviour. If p_attachment_*
-- args are provided, the attachment row is inserted in the same txn with
-- audit.actor='tenant:<id>' -- so the photo lands transactionally with the
-- request + interaction AND its audit event carries the tenant attribution
-- (Phase 4 actor-integrity makes this trustworthy: with auth.uid() null,
-- audit.actor wins; with auth.uid() set, audit.actor is ignored).
--
-- The attachment's storage_path is computed by the caller from the
-- token's account_id + the bytes' sha256, so the path is known before the
-- transaction even starts. The caller uploads the bytes to storage AFTER
-- the RPC returns (an "orphan blob" on RPC failure is harmless and a
-- future cron prunes them).

-- p_attachment_*  : the ORIGINAL bytes the tenant uploaded (often HEIC).
-- p_derivative_*  : optional server-derived JPEG (only set when the
--                   original is HEIC). derived_from on the new row points
--                   back to the original attachment row so the chain of
--                   custody is explicit: this JPEG was computed from that
--                   HEIC at upload, server-side.
create or replace function public.submit_intake_with_attachment(
  p_account_id        uuid,
  p_tenancy_id        uuid,
  p_area_id           uuid,
  p_title             text,
  p_description       text,
  p_severity          text,
  p_occurred_at       timestamptz,
  p_actor             text,
  p_attachment_hash       text,
  p_attachment_mime       text,
  p_attachment_size       bigint,
  p_attachment_path       text,
  p_derivative_hash       text default null,
  p_derivative_mime       text default null,
  p_derivative_size       bigint default null,
  p_derivative_path       text default null
)
returns table (
  maintenance_request_id  uuid,
  interaction_id          uuid,
  attachment_id           uuid,
  derivative_id           uuid,
  deduped                 boolean
)
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_existing_req   uuid;
  v_new_req        uuid;
  v_interaction_id uuid;
  v_attachment_id  uuid;
  v_derivative_id  uuid;
  v_deduped        boolean := false;
begin
  perform set_config('audit.actor', p_actor, true);

  select id into v_existing_req
    from public.maintenance_requests
    where account_id = p_account_id
      and area_id    = p_area_id
      and status     = 'open'
      and title      = p_title
      and deleted_at is null
    limit 1;

  if v_existing_req is not null then
    v_new_req := v_existing_req;
    v_deduped := true;
  else
    insert into public.maintenance_requests
      (account_id, area_id, title, description, severity, status, intake_token)
    values
      (p_account_id, p_area_id, p_title, p_description, p_severity, 'open', p_actor)
    returning id into v_new_req;
  end if;

  insert into public.interactions
    (account_id, actor, party_type, channel, direction, body,
     occurred_at, tenancy_id, maintenance_request_id, area_id)
  values
    (p_account_id, p_actor, 'tenant', 'in_app', 'inbound',
     p_description, p_occurred_at, p_tenancy_id, v_new_req, p_area_id)
  returning id into v_interaction_id;

  if p_attachment_hash is not null then
    insert into public.attachments
      (account_id, entity_type, entity_id, storage_path, content_hash,
       mime_type, size_bytes, uploaded_by)
    values
      (p_account_id, 'maintenance_requests', v_new_req, p_attachment_path,
       p_attachment_hash, p_attachment_mime, p_attachment_size, null)
    returning id into v_attachment_id;

    if p_derivative_hash is not null then
      insert into public.attachments
        (account_id, entity_type, entity_id, storage_path, content_hash,
         mime_type, size_bytes, uploaded_by, derived_from)
      values
        (p_account_id, 'maintenance_requests', v_new_req, p_derivative_path,
         p_derivative_hash, p_derivative_mime, p_derivative_size, null,
         v_attachment_id)
      returning id into v_derivative_id;
    end if;
  end if;

  maintenance_request_id := v_new_req;
  interaction_id         := v_interaction_id;
  attachment_id          := v_attachment_id;
  derivative_id          := v_derivative_id;
  deduped                := v_deduped;
  return next;
end;
$$;

-- ============================================================================
-- (E) Cron generators
-- ============================================================================
--
-- generate_rent_charges: walks rent_schedules due as of p_as_of, inserts
-- the matching charge if not already present (unique partial index
-- enforces no duplicates). Returns the set of charges created in this
-- run. Re-runs and concurrent runs are safe: ON CONFLICT DO NOTHING.
--
-- audit.actor='system:cron:rent' so the audit chain attributes the row to
-- the cron job, distinct from human writes.

-- Names prefixed (o_*) to dodge OUT-name vs column-name parser ambiguity.
-- Postgres treats OUT parameter names as identifiers in scope throughout
-- the function body, including inside ON CONFLICT predicates.
create or replace function public.generate_rent_charges(
  p_account_id uuid,
  p_as_of      timestamptz
)
returns table (
  o_charge_id    uuid,
  o_schedule_id  uuid,
  o_period_start date,
  o_amount_cents bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor text := 'system:cron:rent';
begin
  perform set_config('audit.actor', v_actor, true);

  return query
    with active_schedules as (
      select s.id, s.account_id, s.tenancy_id, s.kind, s.amount_cents, s.currency,
             s.due_day, s.start_date, s.end_date
        from public.rent_schedules s
       where s.account_id = p_account_id
         and s.deleted_at is null
         and s.start_date <= p_as_of::date
         and (s.end_date is null or s.end_date >= p_as_of::date)
    ),
    derived as (
      select
        s.*,
        case
          when extract(day from p_as_of)::int >= s.due_day
          then (date_trunc('month', p_as_of) + make_interval(days => s.due_day - 1))::date
          else (date_trunc('month', p_as_of) - interval '1 month' + make_interval(days => s.due_day - 1))::date
        end as p_start
      from active_schedules s
    ),
    inserted as (
      insert into public.charges
        (account_id, tenancy_id, type, amount_cents, currency, due_date,
         period_start, period_end, description, source_schedule_id)
      select
        d.account_id,
        d.tenancy_id,
        case when d.kind = 'rent' then 'rent' else 'other' end,
        d.amount_cents,
        d.currency,
        d.p_start,
        d.p_start,
        (d.p_start + interval '1 month' - interval '1 day')::date,
        'auto-generated from rent_schedule ' || d.kind,
        d.id
      from derived d
      on conflict (source_schedule_id, period_start)
        where source_schedule_id is not null and period_start is not null
        do nothing
      returning id, source_schedule_id, period_start, amount_cents
    )
    select i.id, i.source_schedule_id, i.period_start, i.amount_cents
      from inserted i;
end;
$$;

grant execute on function public.generate_rent_charges(uuid, timestamptz) to service_role;

-- generate_scheduled_task_runs: walks scheduled_tasks whose next_run has
-- passed and emits a scheduled_task_runs row per (task, period). Same
-- ON CONFLICT shielding.

create or replace function public.generate_scheduled_task_runs(
  p_account_id uuid,
  p_as_of      timestamptz
)
returns table (
  o_run_id       uuid,
  o_task_id      uuid,
  o_period_start date
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor text := 'system:cron:tasks';
begin
  perform set_config('audit.actor', v_actor, true);

  return query
    with due_tasks as (
      select st.id, st.account_id
        from public.scheduled_tasks st
       where st.account_id = p_account_id
         and st.deleted_at is null
         and st.next_run is not null
         and st.next_run <= p_as_of
    ),
    inserted as (
      insert into public.scheduled_task_runs (account_id, task_id, period_start)
      select dt.account_id, dt.id, p_as_of::date
        from due_tasks dt
      on conflict (task_id, period_start) do nothing
      returning id, task_id, period_start
    )
    select i.id, i.task_id, i.period_start from inserted i;
end;
$$;

grant execute on function public.generate_scheduled_task_runs(uuid, timestamptz) to service_role;
