#!/usr/bin/env bash

# Generate the two committed, read-only views of the current local database:
#   - TypeScript types consumed by the API
#   - A schema-only SQL snapshot for humans and code agents
#
# Migrations remain the forward-only change history. These artifacts are the
# read model after every migration has been applied.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

MODE="${1:-write}"
if [[ "$MODE" != "write" && "$MODE" != "--check" ]]; then
  echo "usage: bash scripts/generate-db-artifacts.sh [--check]" >&2
  exit 2
fi

TYPE_TARGET="api/src/supabase/database.types.ts"
SCHEMA_TARGET="db/current-schema.sql"
ARTIFACT_TMP="$(mktemp -d)"
trap 'rm -rf "$ARTIFACT_TMP"' EXIT

if ! supabase --workdir db status >/dev/null 2>&1; then
  echo "FAIL: the local Supabase stack is not running." >&2
  echo "Start it with: (cd db && supabase start)" >&2
  exit 1
fi

supabase --workdir db gen types --local --schema public > "$ARTIFACT_TMP/types.raw.ts"
{
  echo '/**'
  echo ' * GENERATED by scripts/generate-db-artifacts.sh from the fully migrated local DB.'
  echo ' * Do not edit this file directly; change migrations and run `pnpm db:generate`.'
  echo ' */'
  echo
  cat "$ARTIFACT_TMP/types.raw.ts"
} > "$ARTIFACT_TMP/database.types.ts"
pnpm exec prettier --config .prettierrc.json --write "$ARTIFACT_TMP/database.types.ts" >/dev/null

supabase --workdir db db dump \
  --local \
  --schema public \
  --keep-comments \
  --file "$ARTIFACT_TMP/schema.raw.sql" >/dev/null

{
  echo '-- GENERATED by scripts/generate-db-artifacts.sh from the fully migrated local DB.'
  echo '-- Do not edit directly; change migrations and run `pnpm db:generate`.'
  echo
  # pg_dump emits a random psql \restrict token and tool-version comments.
  # They do not describe schema and would make identical dumps differ.
  grep -vE '^-- \\(un)?restrict |^-- Dumped (from|by) ' "$ARTIFACT_TMP/schema.raw.sql"
} > "$ARTIFACT_TMP/current-schema.sql"

if [[ "$MODE" == "--check" ]]; then
  drift=0
  for pair in \
    "$ARTIFACT_TMP/database.types.ts:$TYPE_TARGET" \
    "$ARTIFACT_TMP/current-schema.sql:$SCHEMA_TARGET"; do
    generated="${pair%%:*}"
    committed="${pair#*:}"
    if [[ ! -f "$committed" ]] || ! diff -q "$committed" "$generated" >/dev/null; then
      echo "FAIL: generated DB artifact drift: $committed" >&2
      if [[ -f "$committed" ]]; then
        diff -u "$committed" "$generated" | head -80 || true
      fi
      drift=1
    fi
  done
  if [[ "$drift" -ne 0 ]]; then
    echo "Run 'pnpm db:generate' against a fully migrated local stack and commit the result." >&2
    exit 1
  fi
  echo "OK: generated database types and current schema match the local migrated DB."
  exit 0
fi

cp "$ARTIFACT_TMP/database.types.ts" "$TYPE_TARGET"
cp "$ARTIFACT_TMP/current-schema.sql" "$SCHEMA_TARGET"
echo "Generated $TYPE_TARGET and $SCHEMA_TARGET."
